version: 2
jobs:
  build:
    working_directory: ~/ARMmbed/java-coap

    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:
    - checkout

    # Restore the dependency cache
    - restore_cache:
        key: mbed-java-coap-{{ checksum "pom.xml" }}

    - run: mvn dependency:go-offline install -DskipTests

    # Save dependency cache
    - save_cache:
        key: mbed-java-coap-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

    # Test
    - run: mvn install -P ci

    # publish coverage
    - run: bash <(curl -s https://codecov.io/bash)
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
